<a href="https://colab.research.google.com/github/vinayreddy100/CHATBOT-DEEP-LEARNING-NLP/blob/master/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


In [0]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow_core._api.v2.version' from '/tensorflow-2.1.0/python3.6/tensorflow_core/_api/v2/version/__init__.py'>


In [0]:
# what is tensor ?
#vector generalized to higher dimensions represents n dimensional arrays of base datapoints each tensor has a datatype and shape



In [0]:
# creating tensors
string = tf.Variable("My name is chintu", tf.string)
number = tf.Variable(23, tf.int16)
float3 = tf.Variable(23.23, tf.float64)

In [0]:
# Rank or degree in tensor - number of dimensions involved in tensors
rank1_tensor = tf.Variable(['Bookers BackYard'], tf.string )
rank2_tensor = tf.Variable([['Black Label', '1'], ['Blue Label', '2']], tf.string)

In [0]:
# to determine rank of tensor 
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [0]:
# shape of a tensor tells us how many dimensions we have in each tensor
rank2_tensor.shape

TensorShape([2, 2])

In [0]:
rank1_tensor.shape

TensorShape([1])

In [0]:
# change shape
tensor1 = tf.ones([1,2,3])
print(tensor1)
# reshape existing data to diff shape
tensor2 = tf.reshape(tensor1, [2, 3, 1])
print(tensor2)
tensor3 = tf.reshape(tensor2, [3, -1])
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [0]:
# create a 2d tensor 
matrix = [[1, 2, 3, 4, 5],
          [6, 7,8,9, 0],
          [1, 2, 4, 6, 8],
          [2, 4, 6, 8, 0],
          [2, 4, 6, 7, 8]]
tensor = tf.Variable(matrix, dtype = tf.int32)
print(tf.rank(tensor))
print(tensor.shape)



tf.Tensor(2, shape=(), dtype=int32)
(5, 5)
